Refactor Docker build
cake-build/docker pull request #21
Opened 2020-11-17 10:11 UTC by devlead

This PR refactors how Cake containers are built and deployed, still work in progress.

What's done
- [x] Switch to using Cake.Tool from nuget instead of building Cake again.
- [x] Switch from Azure Pipelines to GitHub Actions
- [x] Reduce number of docker files with help of using parameterized docker file
- [x] Dynamically fetched last 5 versions of Cake and build containers with that
- [x] Dynamically fetch tags from Microsoft official images, currently builds:
  - [x] Linux images
    - mcr.microsoft.com/dotnet/sdk:2.1
    - mcr.microsoft.com/dotnet/sdk:2.1-alpine
    - mcr.microsoft.com/dotnet/sdk:2.1-alpine3.12
    - mcr.microsoft.com/dotnet/sdk:2.1-bionic
    - mcr.microsoft.com/dotnet/sdk:2.1-focal
    - mcr.microsoft.com/dotnet/sdk:2.1-stretch
    - mcr.microsoft.com/dotnet/sdk:3.1
    - mcr.microsoft.com/dotnet/sdk:3.1-alpine
    - mcr.microsoft.com/dotnet/sdk:3.1-alpine3.12
    - mcr.microsoft.com/dotnet/sdk:3.1-bionic
    - mcr.microsoft.com/dotnet/sdk:3.1-buster
    - mcr.microsoft.com/dotnet/sdk:3.1-focal
    - mcr.microsoft.com/dotnet/sdk:5.0
    - mcr.microsoft.com/dotnet/sdk:5.0-alpine
    - mcr.microsoft.com/dotnet/sdk:5.0-alpine-amd64
    - mcr.microsoft.com/dotnet/sdk:5.0-alpine3.12
    - mcr.microsoft.com/dotnet/sdk:5.0-alpine3.12-amd64
    - mcr.microsoft.com/dotnet/sdk:5.0-buster-slim
    - mcr.microsoft.com/dotnet/sdk:5.0-buster-slim-amd64
    - mcr.microsoft.com/dotnet/sdk:5.0-focal
    - mcr.microsoft.com/dotnet/sdk:5.0-focal-amd64
  - [x] Windows Images
    - mcr.microsoft.com/dotnet/sdk:2.1-nanoserver-1809
    - mcr.microsoft.com/dotnet/sdk:2.1-nanoserver-1903
    - mcr.microsoft.com/dotnet/sdk:2.1-nanoserver-1909
    - mcr.microsoft.com/dotnet/sdk:2.1-nanoserver-2004
    - mcr.microsoft.com/dotnet/sdk:2.1-nanoserver-2009
    - mcr.microsoft.com/dotnet/sdk:3.1-nanoserver-1809
    - mcr.microsoft.com/dotnet/sdk:3.1-nanoserver-1903
    - mcr.microsoft.com/dotnet/sdk:3.1-nanoserver-1909
    - mcr.microsoft.com/dotnet/sdk:3.1-nanoserver-2004
    - mcr.microsoft.com/dotnet/sdk:3.1-nanoserver-2009
    - mcr.microsoft.com/dotnet/sdk:5.0-nanoserver-1809
    - mcr.microsoft.com/dotnet/sdk:5.0-nanoserver-1909
    - mcr.microsoft.com/dotnet/sdk:5.0-nanoserver-2004
    - mcr.microsoft.com/dotnet/sdk:5.0-nanoserver-2009
    - mcr.microsoft.com/dotnet/sdk:5.0-windowsservercore-ltsc2019
  - [x] Currently exluded tags  
    - `5.0-alpine3.11` at testing lacked RTM 5 SDK
    - `5.0-nanoserver-1903` at testing lacked RTM 5 SDK

What remains to be done
- [ ] Tag "latest" version
- [ ] Create Ubuntu Image
- [ ] Create Centos Image 
- [ ] Create Fedora Image 
- [ ] Mono images based on above built
- [ ] Bitrise images based on above built
- [ ] Enable docker publish on main  _(might do that as a maintenance PR after this one)_
- [ ] Update readme
- [ ] Upate docs - _separate PR to website_
- [ ] Upate blog - _separate PR to website_

Related issues
- [x] fixes #18 Update to latest version of Cake
- [x] fixes #16 Add .NET Core 3 images.
- [x] fixes #7 Switch to use global tool
- [ ] fixes #6 Create Ubuntu Image
- [ ] fixes #5 Create Centos Image
- [ ] fixes #4 Create Fedora Image
- [x] closes #10 ~~Add Support for the .netCore 2.2 SDK~~ - _Won't fix as it's no longer supported by Microsoft_

2021-11-23 21:38 UTC, gep13 requested changes
A couple minor changes, otherwise LGTM!

2021-11-23 21:38 UTC, gep13 commented on README.md
> +To to pin to a specific version suffix with Cake version i.e. `cakebuild/cake:sdk-6.0` becomes `cakebuild/cake:sdk-6.0-v1.3.0`.
```suggestion
To pin to a specific version suffix with Cake version i.e. `cakebuild/cake:sdk-6.0` becomes `cakebuild/cake:sdk-6.0-v1.3.0`.
```

2021-11-23 21:38 UTC, gep13 commented on README.md
> +Containers are currently build using GitHub Actions.
```suggestion
Containers are currently built using GitHub Actions.
```

2021-11-23 21:38 UTC, gep13 commented on README.md
> +| remove-base-image         | Remove mcr base image after built, useful to conserve space used when building                        |
```suggestion
| remove-base-image         | Remove mcr base image after build, useful to conserve space used when building                        |
```

2021-11-23 21:38 UTC, gep13 commented on build/helpers/docker.cake
> +FilePath        dockerPath          =  Context.Tools.Resolve(IsRunningOnWindows() ? "docker.exe" : "docker")
The spacing seems a little off here...

2021-11-24 07:21 UTC, devlead commented on build/helpers/docker.cake
> +FilePath        dockerPath          =  Context.Tools.Resolve(IsRunningOnWindows() ? "docker.exe" : "docker")
adjusted.

2021-11-27 11:26 UTC, merged